# Generated by Django 4.2.3 on 2023-07-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={},
        ),
        migrations.AlterModelTable(
            name='statistic',
            table='statistics',
        ),
    ]
