# Generated by Django 4.2.3 on 2023-07-12 19:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('holder', '0002_alter_statistic_options_alter_statistic_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Amount billed to the customer, as a string with 3 decimals precision', max_digits=10),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='customerId',
            field=models.IntegerField(default=0, help_text='The customerId is the customer unique identifier'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='The Primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='type',
            field=models.CharField(default='AAA', help_text='The type of message received', max_length=255),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='The message unique identifier'),
        ),
    ]
